add kaggle titanic example
ianlini/feagen pull request #15
Opened 2016-12-09 05:09 UTC by yangarbiter

2016-12-09 06:40 UTC, ianlini requested changes

2016-12-09 06:40 UTC, ianlini commented on examples/titanic/run_model.py
> +    global_f = h5py.File(global_feature_hdf_path, 'r')
unused line

2016-12-09 06:40 UTC, ianlini commented on examples/titanic/run_model.py
> +    global_feature_hdf_path = os.path.join(data_csv_dir, 'data.h5')
unsued line

2016-12-09 06:40 UTC, ianlini commented on examples/titanic/run_model.py
> +    global_f.close()
unused line

2016-12-09 06:40 UTC, ianlini commented on examples/titanic/run_model.py
> +    test_filter = (is_test == 1)
very bad, refer to the lifetime prediction example

2016-12-09 06:40 UTC, ianlini commented on examples/titanic/run_model.py
> +          clf.score(feature[valid_filter], label[valid_filter]))
what score?

2016-12-09 06:40 UTC, ianlini commented on examples/titanic/run_model.py
> +    df.index.name = 'PassengerId'
use rename

2016-12-09 07:04 UTC, yangarbiter commented on examples/titanic/run_model.py
> +          clf.score(feature[valid_filter], label[valid_filter]))
The score defined by  sklearn?  or I should use accuracy?

2016-12-09 07:42 UTC, ianlini commented on examples/titanic/run_model.py
> +          clf.score(feature[valid_filter], label[valid_filter]))
You should say what the score is

2016-12-09 07:45 UTC, ianlini requested changes
It's better to split into 2 files

2016-12-09 07:45 UTC, ianlini commented on examples/titanic/README.rst
> +*******
I use `=` for the first title, and only one line

2016-12-13 06:41 UTC, ianlini commented
Are you going to fix this? 
Switch to use the new API and command line tool.

2016-12-16 02:32 UTC, closed without merging