WIP: Titanic example
ianlini/feagen pull request #26
Opened 2016-12-23 09:08 UTC by yangarbiter

2016-12-27 03:12 UTC, ianlini requested changes

2016-12-27 03:12 UTC, ianlini commented on examples/titanic/.feagenrc/config.yml
> +    global_data.h5
I've changed this

2016-12-27 03:12 UTC, ianlini commented on examples/titanic/model.py
> +    label = np.array(bundle_f['label']['label'])
use `.value`

2016-12-27 03:12 UTC, ianlini commented on examples/titanic/model.py
> +    feature = np.array(bundle_f['features'])
`.value`

2016-12-27 03:12 UTC, ianlini commented on examples/titanic/model.py
> +    bundle_f.close()
use `with`

2016-12-27 03:12 UTC, ianlini commented on examples/titanic/model.py
> +    test_filter = (is_test == 1)
bad code

2016-12-27 03:12 UTC, ianlini commented on examples/titanic/model.py
> +        "prediction.csv")
write variable name

2016-12-27 03:12 UTC, ianlini commented on examples/titanic/model.py
> +          clf.score(feature[valid_filter], label[valid_filter]))
You should say what score is

2016-12-27 03:12 UTC, ianlini commented on examples/titanic/titanic.py
> +        return {'is_test': (temp == -1)}
no `temp`

2016-12-27 03:12 UTC, ianlini commented on examples/titanic/titanic.py
> +        df.loc[valid_id, 'is_valid'] = 1
use bool

2016-12-27 03:12 UTC, ianlini commented on examples/titanic/titanic.py
> +        df.loc[valid_id, 'is_valid'] = 1
or `data_df.index.isin(valid_id)`

2016-12-27 03:12 UTC, ianlini commented on examples/titanic/titanic.py
> +        pclass[np.isnan(pclass)] = 4 # unknown as a class
use pandas to do these operations

2016-12-27 03:12 UTC, ianlini commented on examples/titanic/titanic.py
> +                          .fit_transform(pclass.reshape((-1, 1)))}
think more 
reshape can be eliminated if you add two character

2016-12-27 03:12 UTC, ianlini commented on examples/titanic/titanic.py
> +        age[np.isnan(age)] = np.mean(age[~np.isnan(age)])
use pandas

2016-12-27 03:12 UTC, ianlini commented on examples/titanic/titanic.py
> +        os.path.join(os.path.abspath(__file__), 'data', 'test.csv'))
why not move these to main?

2016-12-27 03:12 UTC, ianlini commented on examples/titanic/titanic.py
> +        os.path.join(os.path.dirname(__file__), 'data', 'global_feature.h5'),
the naming convention of `global_feature.h5` has been changed

2017-01-03 02:26 UTC, ianlini requested changes

2017-01-03 02:26 UTC, ianlini commented on examples/titanic/titanic.py
> +        data_pclass = data_pclass.fillna(4)
use `inplace=True`

2017-01-03 02:26 UTC, ianlini commented on examples/titanic/titanic.py
> +        data_df = data['data_df'].copy() # mutable
what mutable?

2017-01-03 03:18 UTC, yangarbiter commented on examples/titanic/titanic.py
> +        data_df = data['data_df'].copy() # mutable
data['data_df'] is mutable so we should copy before modifying it?

2017-01-03 03:31 UTC, ianlini commented on examples/titanic/titanic.py
> +        data_df = data['data_df'].copy() # mutable
why did you think people will know what you are thinking by just saying "mutable"?

2017-01-03 04:06 UTC, ianlini requested changes

2017-01-03 04:06 UTC, ianlini commented on examples/titanic/titanic.py
> +        data_pclass = data_pclass.fillna(4, inplace=True)
`data_pclass.fillna(4, inplace=True)`

2017-01-10 16:36 UTC, ianlini approved these changes

2017-01-10 16:36 UTC, merged